name: Python Workflow

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python-mypy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy
        pip install .
    - name: Static Analysis with mypy
      run: |
        mypy asciiserialcom tests

  python-unittest:
    strategy:
      matrix:
        pythonversion: ["3.10","3.11"]
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.pythonversion }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.pythonversion }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install .
    - name: Python unittest
      run: |
        coverage run --source=asciiserialcom -m unittest tests
    - name: Python coverage report
      run: |
        coverage report
